source_db:
  type: mysql
  connection:
    host: localhost
    port: 3306
    username: prashant
    password: Qait@123
    database: autoretail
target_db:
  type: mongodb
  connection:
    host: localhost
    port: 27017
    username: prashant-mongo
    password: Qait@123
    database: AutoRetail
